### PR TITLE
Use php-http/promise for the async interface

### PR DESCRIPTION
**Pull request by joelwurtz**
Like discussed in #86

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Shouldn't actually be merged until the Promise getResponse/getException methods are removed from everywhere.

**Comment by joelwurtz** [comment]
Yeah but we need this to be merged to upgrade other libs :)

**Comment by sagikazarmark** [comment]
We can rely on the feature branch for the time being, then magically merge everything at the same time.

**Comment by joelwurtz** [comment]
All pr are done IMO

**Pull request merged**
