### PR TITLE
Added common third party libraries.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Related tickets | Related to https://github.com/php-http/documentation/issues/123 |
| Documentation |  |
| License | MIT |

Related to https://github.com/php-http/documentation/issues/123

### CODE REVIEW

**Comment by dbu** [comment]
hm, i am less sure if we want to put this in here. we link to the httplug.io page as well as the documentation, which both list users. if we duplicate this information too much, we have to update many places for each new user, or whenever a user changes its url or anything.

**Comment by sagikazarmark** [comment]
I agree. Also, the documentation is rather for documenting the project. This is a little bit of self promotion, not documentation. :smile:

**Comment by Nyholm** [comment]
Sorry, I thought you suggested to put it here in the related issue.

**Comment by dbu** [comment]
sorry. hope you agree it makes more sense to keep this in few places?

**Comment by Nyholm** [comment]
Absolutely. Keeping it in 3 places and 3 different formats (md, rst and HTML) is a lot to maintain.

**Pull request closed without merging**
