### PR TITLE
Update PHPSpec to make builds running on PHP 7

### PR DESCRIPTION
**Pull request by sagikazarmark**
Yay, tests are running for PHP 7

### CODE REVIEW

**Comment by dbu** [comment]
should we take php7 out of allowed failures now?

**Comment by sagikazarmark** [comment]
Not sure. PHPSpec is still alpha. Once it gets stable, we can i think.

**Comment by joelwurtz** [comment]
There should be a stable release in one week :)

**Comment by sagikazarmark** [comment]
Great. After that we can remove the dev tag and remove php7 from allow failures.

**Pull request merged**
